DROP TABLE FISCALIZACION.APP_SER CASCADE CONSTRAINTS;

CREATE TABLE FISCALIZACION.APP_SER
(
  APP_GESTION   VARCHAR2(4 BYTE),
  APP_TIPO      VARCHAR2(15 BYTE),
  APP_GERENCIA  VARCHAR2(5 BYTE),
  APP_NUMERO    NUMBER
)
TABLESPACE FISCALIZACION
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE FISCALIZACION.FIS_ACCESO CASCADE CONSTRAINTS;

CREATE TABLE FISCALIZACION.FIS_ACCESO
(
  FIS_ACCESO_ID            NUMBER(18)           NOT NULL,
  FIS_CODIGO_FISCALIZADOR  VARCHAR2(30 BYTE),
  FIS_CARGO                VARCHAR2(50 BYTE),
  FIS_NUM                  NUMBER(10),
  FIS_LSTOPE               VARCHAR2(1 BYTE),
  FIS_USUARIO              VARCHAR2(30 BYTE),
  FIS_FECSYS               DATE,
  CTL_CONTROL_ID           NUMBER(18)
)
TABLESPACE FISCALIZACION
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


DROP TABLE FISCALIZACION.FIS_ALCANCE CASCADE CONSTRAINTS;

CREATE TABLE FISCALIZACION.FIS_ALCANCE
(
  ALC_ALCANCE_ID      NUMBER(18),
  ALC_TIPO_ALCANCE    VARCHAR2(30 BYTE)         NOT NULL,
  ALC_TIPO_TRAMITE    VARCHAR2(30 BYTE)         NOT NULL,
  ALC_GESTION         VARCHAR2(4 BYTE)          NOT NULL,
  ALC_ADUANA          VARCHAR2(3 BYTE),
  ALC_NUMERO          NUMBER(20)                NOT NULL,
  ALC_FECHA           DATE,
  ALC_PROVEEDOR       VARCHAR2(50 BYTE),
  ALC_PAIS            VARCHAR2(10 BYTE),
  ALC_TIPO_DOCUMENTO  VARCHAR2(30 BYTE),
  ALC_NUM             NUMBER(10),
  ALC_LSTOPE          VARCHAR2(1 BYTE)          NOT NULL,
  ALC_USUARIO         VARCHAR2(30 BYTE),
  ALC_FECSYS          DATE,
  CTL_CONTROL_ID      NUMBER(18),
  ALC_TIPO_ETAPA      VARCHAR2(30 BYTE)
)
TABLESPACE FISCALIZACION
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE FISCALIZACION.FIS_ALCANCE_AMP CASCADE CONSTRAINTS;

CREATE TABLE FISCALIZACION.FIS_ALCANCE_AMP
(
  AMP_ALCANCEAMP_ID  NUMBER(18)                 NOT NULL,
  ALC_ALCANCE_ID     NUMBER(18)                 NOT NULL,
  CTL_CONTROL_ID     NUMBER(18),
  AMP_NUM            NUMBER(10),
  AMP_LSTOPE         VARCHAR2(1 BYTE)           NOT NULL,
  AMP_USUARIO        VARCHAR2(30 BYTE),
  AMP_FECSYS         DATE,
  AMP_TIPO_ETAPA     VARCHAR2(30 BYTE)
)
TABLESPACE FISCALIZACION
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


ALTER TABLE FISCALIZACION.FIS_ALCANCE_ITEM
 DROP PRIMARY KEY CASCADE;

DROP TABLE FISCALIZACION.FIS_ALCANCE_ITEM CASCADE CONSTRAINTS;

CREATE TABLE FISCALIZACION.FIS_ALCANCE_ITEM
(
  ALC_ALCANCE_ID   NUMBER(18)                   NOT NULL,
  ALI_NUMERO_ITEM  NUMBER(10)                   NOT NULL,
  ALI_OBS_VALOR    VARCHAR2(5 BYTE),
  ALI_OBS_PARTIDA  VARCHAR2(5 BYTE),
  ALI_OBS_ORIGEN   VARCHAR2(5 BYTE),
  ALI_NUM          NUMBER(10),
  ALI_LSTOPE       VARCHAR2(1 BYTE)             NOT NULL,
  ALI_USUARIO      VARCHAR2(30 BYTE),
  ALI_FECSYS       DATE,
  ALI_OBS_OTRO     VARCHAR2(5 BYTE),
  ALI_TIPO_ETAPA   VARCHAR2(30 BYTE)
)
TABLESPACE FISCALIZACION
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE FISCALIZACION.FIS_ANULACION CASCADE CONSTRAINTS;

CREATE TABLE FISCALIZACION.FIS_ANULACION
(
  CTL_CONTROL_ID     NUMBER(18),
  ANU_JUSTIFICACION  VARCHAR2(300 BYTE),
  ANU_NUM            NUMBER(10),
  ANU_LSTOPE         VARCHAR2(1 BYTE),
  ANU_USUARIO        VARCHAR2(30 BYTE),
  ANU_FECSYS         DATE
)
TABLESPACE FISCALIZACION
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


DROP TABLE FISCALIZACION.FIS_CONCLUSION CASCADE CONSTRAINTS;

CREATE TABLE FISCALIZACION.FIS_CONCLUSION
(
  CTL_CONTROL_ID     NUMBER(18)                 NOT NULL,
  CON_TIPO_DOC_CON   VARCHAR2(100 BYTE),
  CON_NUM_DOC_CON    VARCHAR2(100 BYTE),
  CON_FECHA_DOC_CON  DATE,
  CON_NUM            NUMBER(10),
  CON_LSTOPE         VARCHAR2(1 BYTE),
  CON_USUARIO        VARCHAR2(30 BYTE),
  CON_FECSYS         DATE
)
TABLESPACE FISCALIZACION
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE FISCALIZACION.FIS_CONTROL CASCADE CONSTRAINTS;

CREATE TABLE FISCALIZACION.FIS_CONTROL
(
  CTL_CONTROL_ID           NUMBER(18)           NOT NULL,
  CTL_COD_GESTION          VARCHAR2(4 BYTE),
  CTL_COD_TIPO             VARCHAR2(50 BYTE),
  CTL_COD_GERENCIA         VARCHAR2(10 BYTE),
  CTL_COD_NUMERO           NUMBER(10),
  CTL_TIPO_DOCUMENTO       VARCHAR2(50 BYTE),
  CTL_NRO_DOCUMENTO        VARCHAR2(100 BYTE),
  CTL_FECHA_DOCUMENTO      DATE,
  CTL_OBS_DOCUMENTO        VARCHAR2(500 BYTE),
  CTL_RIESGO_IDENTIFICADO  VARCHAR2(30 BYTE),
  CTL_TIPO_DOC_IDENTIDAD   VARCHAR2(10 BYTE),
  CTL_NIT                  NUMBER(18),
  CTL_RAZON_SOCIAL         VARCHAR2(100 BYTE),
  CTL_CI                   NUMBER(12),
  CTL_CI_EXP               VARCHAR2(5 BYTE),
  CTL_NOMBRES              VARCHAR2(30 BYTE),
  CTL_APPAT                VARCHAR2(30 BYTE),
  CTL_APMAT                VARCHAR2(30 BYTE),
  CTL_DIRECCION            VARCHAR2(300 BYTE),
  CTL_ACTIVIDAD_PRINCIPAL  VARCHAR2(300 BYTE),
  CTL_AMP_CORRELATIVO      NUMBER(5),
  CTL_NUM                  NUMBER(5)            NOT NULL,
  CTL_LSTOPE               VARCHAR2(1 BYTE),
  CTL_USUARIO              VARCHAR2(30 BYTE),
  CTL_FECSYS               DATE,
  CTL_TIPO_OPERADOR        VARCHAR2(30 BYTE),
  CTL_TRIBTODOS            VARCHAR2(10 BYTE),
  CTL_TRIBGA               VARCHAR2(10 BYTE),
  CTL_TRIBIVA              VARCHAR2(10 BYTE),
  CTL_TRIBICE              VARCHAR2(10 BYTE),
  CTL_TRIBIEHD             VARCHAR2(10 BYTE),
  CTL_TRIBICD              VARCHAR2(10 BYTE),
  CTL_TRIBNOAPLICA         VARCHAR2(10 BYTE),
  CTL_PERIODO              VARCHAR2(30 BYTE),
  CTL_RIESGODELITO         VARCHAR2(10 BYTE),
  CTL_RIESGOSUBVAL         VARCHAR2(10 BYTE),
  CTL_RIESGOCLAS           VARCHAR2(10 BYTE),
  CTL_RIESGOCONTRAB        VARCHAR2(10 BYTE),
  CTL_AMP_CONTROL          VARCHAR2(15 BYTE),
  CTL_PERIODO_SOLICITAR    VARCHAR2(30 BYTE)
)
TABLESPACE FISCALIZACION
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE FISCALIZACION.FIS_CON_ACTAINTER CASCADE CONSTRAINTS;

CREATE TABLE FISCALIZACION.FIS_CON_ACTAINTER
(
  CTL_CONTROL_ID            NUMBER(18)          NOT NULL,
  CAI_ACTA_INTERV           VARCHAR2(30 BYTE),
  CAI_FECHA_ACTA_INTERV     DATE,
  CAI_TIPO_ILICITO          VARCHAR2(30 BYTE),
  CAI_CI_REMISION           VARCHAR2(30 BYTE),
  CAI_FECHA_CI_REMISION     DATE,
  CAI_FECHA_PRES_DESCARGOS  DATE,
  CAI_INF_DESCARGO          VARCHAR2(30 BYTE),
  CAI_FECHA_INF_DESCARGO    DATE,
  CAI_NUMERO_RFS            VARCHAR2(30 BYTE),
  CAI_FECHA_RFS             DATE,
  CAI_NUMERO_RS             VARCHAR2(30 BYTE),
  CAI_FECHA_RS              DATE,
  CAI_NUM                   NUMBER(10),
  CAI_LSTOPE                VARCHAR2(1 BYTE),
  CAI_USUARIO               VARCHAR2(30 BYTE),
  CAI_FECSYS                DATE,
  CAI_NUMERO_INFORME        VARCHAR2(30 BYTE),
  CAI_FECHA_INFORME         DATE,
  CAI_GERENCIA_LEGAL        VARCHAR2(50 BYTE),
  CAI_FECHA_NOT_AI          DATE,
  CAI_TIPO_NOT_AI           VARCHAR2(50 BYTE),
  CAI_RESULTADO_DES         VARCHAR2(50 BYTE),
  CAI_TIPO_RESOLUCION       VARCHAR2(50 BYTE)
)
TABLESPACE FISCALIZACION
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE FISCALIZACION.FIS_CON_AUTOINICIAL CASCADE CONSTRAINTS;

CREATE TABLE FISCALIZACION.FIS_CON_AUTOINICIAL
(
  CTL_CONTROL_ID            NUMBER(18)          NOT NULL,
  CAS_NUMERO_AISC           VARCHAR2(30 BYTE),
  CAS_FECHA_NOTIFICACION    DATE,
  CAS_FECHA_PRES_DESCARGOS  DATE,
  CAS_INF_DESCARGO          VARCHAR2(30 BYTE),
  CAS_FECHA_INF_DESCARGO    DATE,
  CAS_NUMERO_RFS            VARCHAR2(30 BYTE),
  CAS_FECHA_RFS             DATE,
  CAS_CI_REMISION_GR        VARCHAR2(30 BYTE),
  CAS_FECHA_CI              DATE,
  CAS_NUMERO_RS             VARCHAR2(30 BYTE),
  CAS_FECHA_RS              DATE,
  CAS_NUM                   NUMBER(10),
  CAS_LSTOPE                VARCHAR2(1 BYTE),
  CAS_USUARIO               VARCHAR2(30 BYTE),
  CAS_FECSYS                DATE,
  CAS_NUMERO_INFORME        VARCHAR2(30 BYTE),
  CAS_FECHA_INFORME         DATE,
  CAS_GERENCIA_LEGAL        VARCHAR2(50 BYTE)
)
TABLESPACE FISCALIZACION
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE FISCALIZACION.FIS_CON_RESADMIN CASCADE CONSTRAINTS;

CREATE TABLE FISCALIZACION.FIS_CON_RESADMIN
(
  CTL_CONTROL_ID          NUMBER(18)            NOT NULL,
  CRA_FECHA_PAGO_CUINI    DATE,
  CRA_MONTO_PAGO_CUOINI   NUMBER(18),
  CRA_NUMERO_RA           VARCHAR2(30 BYTE),
  CRA_FECHA_RA            DATE,
  CRA_CI_REMISION_SET     VARCHAR2(30 BYTE),
  CRA_FECHA_REMISION_SET  DATE,
  CRA_SALDO_POR_COBRAR    NUMBER(18),
  CRA_NUM                 NUMBER(10),
  CRA_LSTOPE              VARCHAR2(1 BYTE),
  CRA_USUARIO             VARCHAR2(30 BYTE),
  CRA_FECSYS              DATE,
  CRA_NUMERO_INFORME      VARCHAR2(30 BYTE),
  CRA_FECHA_INFORME       DATE,
  CRA_RUP_GESTION         VARCHAR2(4 BYTE),
  CRA_RUP_ADUANA          VARCHAR2(4 BYTE),
  CRA_RUP_NUMERO          VARCHAR2(10 BYTE),
  CRA_GERENCIA_LEGAL      VARCHAR2(50 BYTE)
)
TABLESPACE FISCALIZACION
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE FISCALIZACION.FIS_CON_RESDETER CASCADE CONSTRAINTS;

CREATE TABLE FISCALIZACION.FIS_CON_RESDETER
(
  CTL_CONTROL_ID          NUMBER(18)            NOT NULL,
  CRD_RD_FINAL            VARCHAR2(30 BYTE),
  CRD_FECHA_NOT_RD_FINAL  DATE,
  CRD_NUM                 NUMBER(10),
  CRD_LSTOPE              VARCHAR2(1 BYTE),
  CRD_USUARIO             VARCHAR2(30 BYTE),
  CRD_FECSYS              DATE,
  CRD_NUMERO_INFORME      VARCHAR2(30 BYTE),
  CRD_FECHA_INFORME       DATE
)
TABLESPACE FISCALIZACION
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE FISCALIZACION.FIS_CON_VISCARGO CASCADE CONSTRAINTS;

CREATE TABLE FISCALIZACION.FIS_CON_VISCARGO
(
  CTL_CONTROL_ID          NUMBER(18)            NOT NULL,
  CVC_TIPO_NOTIFICACION   VARCHAR2(30 BYTE),
  CVC_FECHA_NOTIFICACION  DATE,
  CVC_FECHA_PRESENTACION  DATE,
  CVC_INF_DESCARGO        VARCHAR2(30 BYTE),
  CVC_FECHA_DESCARGO      DATE,
  CVC_RD_FINAL            VARCHAR2(30 BYTE),
  CVC_FECHA_NOT_RD_FINAL  DATE,
  CVC_CI_REMISION         VARCHAR2(30 BYTE),
  CVC_FECHA_CI_REMISION   DATE,
  CVC_NUMERO_RD           VARCHAR2(30 BYTE),
  CVC_FECHA_RD            DATE,
  CVC_NUM                 NUMBER(10),
  CVC_LSTOPE              VARCHAR2(1 BYTE),
  CVC_USUARIO             VARCHAR2(30 BYTE),
  CVC_FECSYS              DATE,
  CVC_NUMERO_INFORME      VARCHAR2(30 BYTE),
  CVC_FECHA_INFORME       DATE,
  CVC_NUMERO_VC           VARCHAR2(30 BYTE),
  CVC_FECHA_VC            DATE,
  CVC_TIPO_RD             VARCHAR2(100 BYTE),
  CVC_GERENCIA_LEGAL      VARCHAR2(50 BYTE)
)
TABLESPACE FISCALIZACION
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE FISCALIZACION.FIS_ESTADO CASCADE CONSTRAINTS;

CREATE TABLE FISCALIZACION.FIS_ESTADO
(
  CTL_CONTROL_ID  NUMBER(18)                    NOT NULL,
  EST_ESTADO      VARCHAR2(30 BYTE),
  EST_NUM         NUMBER(10),
  EST_LSTOPE      VARCHAR2(1 BYTE),
  EST_USUARIO     VARCHAR2(30 BYTE),
  EST_FECSYS      DATE
)
TABLESPACE FISCALIZACION
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE FISCALIZACION.FIS_FAP CASCADE CONSTRAINTS;

CREATE TABLE FISCALIZACION.FIS_FAP
(
  SAD_REG_YEAR     VARCHAR2(4 BYTE),
  KEY_CUO          VARCHAR2(5 BYTE),
  SAD_REG_SERIAL   VARCHAR2(1 BYTE),
  SAD_REG_NBER     NUMBER,
  FAP_NRO_CONTROL  VARCHAR2(50 BYTE),
  FAP_NUM          NUMBER,
  FAP_TRAMITE      VARCHAR2(30 BYTE),
  FAP_ESTADO       VARCHAR2(50 BYTE)
)
TABLESPACE FISCALIZACION
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


DROP TABLE FISCALIZACION.FIS_FISCALIZADOR CASCADE CONSTRAINTS;

CREATE TABLE FISCALIZACION.FIS_FISCALIZADOR
(
  FIS_FISCALIZADOR_ID      NUMBER(18)           NOT NULL,
  FIS_CODIGO_FISCALIZADOR  VARCHAR2(30 BYTE),
  FIS_CARGO                VARCHAR2(50 BYTE),
  FIS_NUM                  NUMBER(10),
  FIS_LSTOPE               VARCHAR2(1 BYTE),
  FIS_USUARIO              VARCHAR2(30 BYTE),
  FIS_FECSYS               DATE,
  CTL_CONTROL_ID           NUMBER(18)
)
TABLESPACE FISCALIZACION
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE FISCALIZACION.FIS_INFO_NOTIFICACION CASCADE CONSTRAINTS;

CREATE TABLE FISCALIZACION.FIS_INFO_NOTIFICACION
(
  INN_INFNOT_ID         NUMBER(18)              NOT NULL,
  INN_PLAZO_CONCLUSION  NUMBER(10),
  INN_1                 VARCHAR2(5 BYTE),
  INN_2                 VARCHAR2(5 BYTE),
  INN_3                 VARCHAR2(5 BYTE),
  INN_4                 VARCHAR2(5 BYTE),
  INN_5                 VARCHAR2(5 BYTE),
  INN_6                 VARCHAR2(5 BYTE),
  INN_7                 VARCHAR2(5 BYTE),
  INN_8                 VARCHAR2(5 BYTE),
  INN_9                 VARCHAR2(5 BYTE),
  INN_10                VARCHAR2(5 BYTE),
  INN_11                VARCHAR2(5 BYTE),
  INN_12                VARCHAR2(300 BYTE),
  INN_13                VARCHAR2(300 BYTE),
  INN_14                VARCHAR2(300 BYTE),
  INN_15                VARCHAR2(300 BYTE),
  INN_16                VARCHAR2(300 BYTE),
  INN_17                VARCHAR2(300 BYTE),
  INN_18                VARCHAR2(300 BYTE),
  INN_19                VARCHAR2(300 BYTE),
  INN_20                VARCHAR2(300 BYTE),
  INN_21                VARCHAR2(300 BYTE),
  INN_NUM               NUMBER(10),
  INN_LSTOPE            VARCHAR2(1 BYTE),
  INN_USUARIO           VARCHAR2(30 BYTE),
  INN_FECSYS            DATE,
  CTL_CONTROL_ID        NUMBER(18)
)
TABLESPACE FISCALIZACION
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE FISCALIZACION.FIS_NOTIFICACION CASCADE CONSTRAINTS;

CREATE TABLE FISCALIZACION.FIS_NOTIFICACION
(
  CTL_CONTROL_ID          NUMBER(18),
  NOT_FECHA_NOTIFICACION  DATE,
  NOT_TIPO_NOTIFICACION   VARCHAR2(30 BYTE),
  NOT_OBS_NOTIFICACION    VARCHAR2(100 BYTE),
  NOT_NUM                 NUMBER(10),
  NOT_LSTOPE              VARCHAR2(1 BYTE),
  NOT_USUARIO             VARCHAR2(30 BYTE),
  NOT_FECSYS              DATE
)
TABLESPACE FISCALIZACION
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE FISCALIZACION.FIS_NOT_CONCLUSION CASCADE CONSTRAINTS;

CREATE TABLE FISCALIZACION.FIS_NOT_CONCLUSION
(
  CTL_CONTROL_ID          NUMBER(18)            NOT NULL,
  NDC_FECHA_NOTIFICACION  DATE,
  NDC_TIPO_NOTIFICACION   VARCHAR2(30 BYTE),
  NDC_NUM                 NUMBER(10),
  NDC_LSTOPE              VARCHAR2(1 BYTE),
  NDC_USUARIO             VARCHAR2(30 BYTE),
  NDC_FECSYS              DATE
)
TABLESPACE FISCALIZACION
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE FISCALIZACION.FIS_RESULTADOS CASCADE CONSTRAINTS;

CREATE TABLE FISCALIZACION.FIS_RESULTADOS
(
  RES_DUI           VARCHAR2(30 BYTE)           NOT NULL,
  RES_NUMERO_ITEM   NUMBER(10),
  RES_PARTIDA       VARCHAR2(30 BYTE),
  RES_FOB_USD       NUMBER(18,2),
  RES_FLETE_USD     NUMBER(18,2),
  RES_SEGURO_USD    NUMBER(18,2),
  RES_OTROS_USD     NUMBER(18,2),
  RES_CIF_USD       NUMBER(18,2),
  RES_CIF_BOB       NUMBER(18,2),
  RES_CONTRAV       NUMBER(18),
  RES_ILICITO       VARCHAR2(100 BYTE),
  RES_OBSERVACION   VARCHAR2(200 BYTE),
  RES_NUM           NUMBER(10),
  RES_LSTOPE        VARCHAR2(1 BYTE),
  RES_USUARIO       VARCHAR2(30 BYTE),
  RES_FECSYS        DATE,
  KEY_YEAR          VARCHAR2(4 BYTE),
  KEY_CUO           VARCHAR2(5 BYTE),
  KEY_DEC           VARCHAR2(17 BYTE),
  KEY_NBER          VARCHAR2(13 BYTE),
  RES_CONTRAVORDEN  NUMBER(18),
  ALC_ALCANCE_ID    NUMBER(18)
)
TABLESPACE FISCALIZACION
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE FISCALIZACION.FIS_RESULTADOS_TRAMITE CASCADE CONSTRAINTS;

CREATE TABLE FISCALIZACION.FIS_RESULTADOS_TRAMITE
(
  ALC_ALCANCE_ID    NUMBER(18),
  RET_MERCANCIA     VARCHAR2(100 BYTE),
  RET_FOB_USD       NUMBER(18,2),
  RET_FLETE_USD     NUMBER(18,2),
  RET_SEGURO_USD    NUMBER(18,2),
  RET_OTROS_USD     NUMBER(18,2),
  RET_CIF_USD       NUMBER(18,2),
  RET_CIF_BOB       NUMBER(18,2),
  RET_CIF_UFV       NUMBER(18,2),
  RET_NUM           NUMBER(10),
  RET_LSTOPE        VARCHAR2(1 BYTE),
  RET_USUARIO       VARCHAR2(30 BYTE),
  RET_FECSYS        DATE,
  RET_ILICITO       VARCHAR2(100 BYTE),
  RET_CONTRAVORDEN  NUMBER(18)
)
TABLESPACE FISCALIZACION
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX FISCALIZACION.APP_SER_IDX ON FISCALIZACION.APP_SER
(APP_GESTION, APP_TIPO, APP_GERENCIA)
LOGGING
TABLESPACE FISCALIZACION
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX FISCALIZACION.FIS_ALCANCE_AMP_IDX ON FISCALIZACION.FIS_ALCANCE_AMP
(AMP_ALCANCEAMP_ID, CTL_CONTROL_ID, ALC_ALCANCE_ID, AMP_NUM)
LOGGING
TABLESPACE FISCALIZACION
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX FISCALIZACION.FIS_ALCANCE_ITEM_PK ON FISCALIZACION.FIS_ALCANCE_ITEM
(ALC_ALCANCE_ID, ALI_NUMERO_ITEM, ALI_NUM)
LOGGING
TABLESPACE FISCALIZACION
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX FISCALIZACION.FIS_ALCANCE_PK ON FISCALIZACION.FIS_ALCANCE
(ALC_ALCANCE_ID, ALC_TIPO_ALCANCE, ALC_TIPO_TRAMITE, ALC_GESTION, ALC_NUM, 
CTL_CONTROL_ID)
LOGGING
TABLESPACE FISCALIZACION
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX FISCALIZACION.FIS_FAP_IDX ON FISCALIZACION.FIS_FAP
(SAD_REG_YEAR, KEY_CUO, SAD_REG_SERIAL, SAD_REG_NBER, FAP_NUM, 
FAP_TRAMITE)
LOGGING
TABLESPACE FISCALIZACION
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE FISCALIZACION.FIS_ALCANCE ADD (
  CONSTRAINT FIS_ALCANCE_PK
  UNIQUE (ALC_ALCANCE_ID, ALC_TIPO_ALCANCE, ALC_TIPO_TRAMITE, ALC_GESTION, ALC_NUM, CTL_CONTROL_ID)
  USING INDEX FISCALIZACION.FIS_ALCANCE_PK
  ENABLE VALIDATE);

ALTER TABLE FISCALIZACION.FIS_ALCANCE_ITEM ADD (
  CONSTRAINT FIS_ALCANCE_ITEM_PK
  PRIMARY KEY
  (ALC_ALCANCE_ID, ALI_NUMERO_ITEM, ALI_NUM)
  USING INDEX FISCALIZACION.FIS_ALCANCE_ITEM_PK
  ENABLE VALIDATE);

GRANT SELECT ON FISCALIZACION.APP_SER TO CCORTEZ;

GRANT SELECT ON FISCALIZACION.FIS_ACCESO TO CCORTEZ;

GRANT SELECT ON FISCALIZACION.FIS_ALCANCE TO CCORTEZ;

GRANT SELECT ON FISCALIZACION.FIS_ALCANCE_AMP TO CCORTEZ;

GRANT SELECT ON FISCALIZACION.FIS_ALCANCE_ITEM TO CCORTEZ;

GRANT SELECT ON FISCALIZACION.FIS_ANULACION TO CCORTEZ;

GRANT SELECT ON FISCALIZACION.FIS_CONCLUSION TO CCORTEZ;

GRANT SELECT ON FISCALIZACION.FIS_CONTROL TO CCORTEZ;

GRANT SELECT ON FISCALIZACION.FIS_CON_ACTAINTER TO CCORTEZ;

GRANT SELECT ON FISCALIZACION.FIS_CON_AUTOINICIAL TO CCORTEZ;

GRANT SELECT ON FISCALIZACION.FIS_CON_RESADMIN TO CCORTEZ;

GRANT SELECT ON FISCALIZACION.FIS_CON_RESDETER TO CCORTEZ;

GRANT SELECT ON FISCALIZACION.FIS_CON_VISCARGO TO CCORTEZ;

GRANT SELECT ON FISCALIZACION.FIS_ESTADO TO CCORTEZ;

GRANT SELECT ON FISCALIZACION.FIS_FAP TO CCORTEZ;

GRANT SELECT ON FISCALIZACION.FIS_FISCALIZADOR TO CCORTEZ;

GRANT SELECT ON FISCALIZACION.FIS_INFO_NOTIFICACION TO CCORTEZ;

GRANT SELECT ON FISCALIZACION.FIS_NOTIFICACION TO CCORTEZ;

GRANT SELECT ON FISCALIZACION.FIS_NOT_CONCLUSION TO CCORTEZ;

GRANT SELECT ON FISCALIZACION.FIS_RESULTADOS TO CCORTEZ;

GRANT SELECT ON FISCALIZACION.FIS_RESULTADOS_TRAMITE TO CCORTEZ;

GRANT SELECT ON FISCALIZACION.APP_SER TO CONSULTA_TODO_FISCALIZACION;

GRANT SELECT ON FISCALIZACION.FIS_ACCESO TO CONSULTA_TODO_FISCALIZACION;

GRANT SELECT ON FISCALIZACION.FIS_ALCANCE TO CONSULTA_TODO_FISCALIZACION;

GRANT SELECT ON FISCALIZACION.FIS_ALCANCE_AMP TO CONSULTA_TODO_FISCALIZACION;

GRANT SELECT ON FISCALIZACION.FIS_ALCANCE_ITEM TO CONSULTA_TODO_FISCALIZACION;

GRANT SELECT ON FISCALIZACION.FIS_ANULACION TO CONSULTA_TODO_FISCALIZACION;

GRANT SELECT ON FISCALIZACION.FIS_CONCLUSION TO CONSULTA_TODO_FISCALIZACION;

GRANT SELECT ON FISCALIZACION.FIS_CONTROL TO CONSULTA_TODO_FISCALIZACION;

GRANT SELECT ON FISCALIZACION.FIS_CON_ACTAINTER TO CONSULTA_TODO_FISCALIZACION;

GRANT SELECT ON FISCALIZACION.FIS_CON_AUTOINICIAL TO CONSULTA_TODO_FISCALIZACION;

GRANT SELECT ON FISCALIZACION.FIS_CON_RESADMIN TO CONSULTA_TODO_FISCALIZACION;

GRANT SELECT ON FISCALIZACION.FIS_CON_RESDETER TO CONSULTA_TODO_FISCALIZACION;

GRANT SELECT ON FISCALIZACION.FIS_CON_VISCARGO TO CONSULTA_TODO_FISCALIZACION;

GRANT SELECT ON FISCALIZACION.FIS_ESTADO TO CONSULTA_TODO_FISCALIZACION;

GRANT SELECT ON FISCALIZACION.FIS_FAP TO CONSULTA_TODO_FISCALIZACION;

GRANT SELECT ON FISCALIZACION.FIS_FISCALIZADOR TO CONSULTA_TODO_FISCALIZACION;

GRANT SELECT ON FISCALIZACION.FIS_INFO_NOTIFICACION TO CONSULTA_TODO_FISCALIZACION;

GRANT SELECT ON FISCALIZACION.FIS_NOTIFICACION TO CONSULTA_TODO_FISCALIZACION;

GRANT SELECT ON FISCALIZACION.FIS_NOT_CONCLUSION TO CONSULTA_TODO_FISCALIZACION;

GRANT SELECT ON FISCALIZACION.FIS_RESULTADOS TO CONSULTA_TODO_FISCALIZACION;

GRANT SELECT ON FISCALIZACION.FIS_RESULTADOS_TRAMITE TO CONSULTA_TODO_FISCALIZACION;
